server:
  host: "localhost"
  port: 8081
  session: 
    secret_key: abcdefg
    age_second: 86400
    http_only: true
    secure: false
  rate_limit:
    all: 
      second: 1
      max_request: 1000
    ip:
      second: 1
      max_request: 20
    repeat: 
      second: 3
      max_request: 1
database:
  host: "chatroom.cjgweugeut92.ap-northeast-1.rds.amazonaws.com"
  user: "postgres"
  password: "..."
  name: ""
  port: 5432
  sslmode: ""
redis:
  address: "..."
  password: ""
  db: 0
  max_connection: 30
  min_connection: 5
logger:
  level: "info"

  
